package:
  name: mkbase
  version: 0.0.1

build:
  number: 1

requirements:
  build:
   - python 2.*

  run:
    - python 2.*
    - numpy <=1.9.*
    - pandas <=0.16.*
    - sqlalchemy
    - psycopg2

test:
  imports:
    - mkbase

about:
  license: BSD
